version: '3.8'

services:
  web:
    image: ghcr.io/knoepsim/beerpong-webapp-web:latest
    container_name: beerpong-web
    restart: always
    environment:
      - NODE_ENV=production
      # This points to the Docker container 'api' below.
      # No need to expose the API port to the outside world!
      - API_INTERNAL_URL=http://api:8000
    depends_on:
      - api
    # Only the web frontend needs to be connected to the cloudflare tunnel
    # Either expose port 3000 to the local network for cloudflared to pick up, 
    # or attach cloudflared to this docker network.
    ports:
      - "3000:3000"
    networks:
      - beerpong-network

  api:
    image: ghcr.io/knoepsim/beerpong-webapp-api:latest
    container_name: beerpong-api
    restart: always
    # We do NOT expose ports to the host machine!
    # The frontend container will communicate with it over the internal docker network.
    networks:
      - beerpong-network

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # If your GHCR is private, you need to mount a config.json with your github PAT
      # - /root/.docker/config.json:/config.json
    environment:
      - WATCHTOWER_CLEANUP=true
      # Check for updates every 5 minutes (300 seconds)
      - WATCHTOWER_POLL_INTERVAL=300
    command: beerpong-web beerpong-api

networks:
  beerpong-network:
    driver: bridge
