sonar.projectKey=knoepsim_beerpong-webapp
sonar.organization=knoepsim


# This is the name and version displayed in the SonarCloud UI.
#sonar.projectName=beerpong-webapp
#sonar.projectVersion=1.0


# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
#sonar.sources=.

# Encoding of the source code. Default is default system encoding
sonar.sourceEncoding=UTF-8

# Python Version
sonar.python.version=3.12

# Test Coverage
sonar.javascript.lcov.reportPaths=apps/web/coverage/lcov.info
sonar.exclusions=apps/web/components/ui/**,apps/web/.next/**,apps/web/coverage/**,apps/web/tests/**,apps/web/playwright-report/**,apps/web/test-results/**
sonar.coverage.exclusions=**/*.config.*,**/*setup*.*,**/Dockerfile,**/*.xml,**/*.yml,**/*.json,apps/api/**,apps/web/app/**