"""add checkin and registration dates

Revision ID: 06c7ffead398
Revises: 6d34f2838f0a
Create Date: 2026-07-28 22:32:14.886457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06c7ffead398'
down_revision: Union[str, None] = '6d34f2838f0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournament_teams', sa.Column('is_checked_in', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('tournaments', sa.Column('registration_end_time', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tournaments', sa.Column('checkin_start_time', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournaments', 'checkin_start_time')
    op.drop_column('tournaments', 'registration_end_time')
    op.drop_column('tournament_teams', 'is_checked_in')
    # ### end Alembic commands ###
