"""add_is_deleted_to_team

Revision ID: 0bb5f8307581
Revises: 8774f85a5678
Create Date: 2026-07-25 22:19:20.403671
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bb5f8307581'
down_revision: Union[str, None] = '8774f85a5678'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'is_deleted')
    # ### end Alembic commands ###
