"""add_system_admin_flag

Revision ID: 6d34f2838f0a
Revises: b4bc5a548872
Create Date: 2026-07-26 12:52:30.985503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d34f2838f0a'
down_revision: Union[str, None] = 'b4bc5a548872'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_system_admin', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_system_admin')
    # ### end Alembic commands ###
