"""add_tournament_invite_token

Revision ID: 72baa1e5d10c
Revises: 02a241bca6e7
Create Date: 2026-08-03 22:28:38.285005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72baa1e5d10c'
down_revision: Union[str, None] = '02a241bca6e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournaments', sa.Column('invite_token', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_tournaments_invite_token'), 'tournaments', ['invite_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tournaments_invite_token'), table_name='tournaments')
    op.drop_column('tournaments', 'invite_token')
    # ### end Alembic commands ###
